[package]
name = "pointeuse2"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.12", features = ["blocking", "cookies"] }
scraper = "0.22.0"
urlencoding = "2.1.3"
serde_json = "1.0.138"
base64 = "0.22.1"